# Generated by Django 4.2.17 on 2024-12-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AerolotBooking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
    ]
