# Generated by Django 4.2.17 on 2025-01-02 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AerolotBooking", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="luggage",),
        migrations.RemoveField(model_name="booking", name="passanger_name",),
        migrations.RemoveField(model_name="booking", name="passanger_surname",),
        migrations.AddField(
            model_name="booking",
            name="passanger_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="passengers",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
