# Generated by Django 4.2.17 on 2025-01-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AerolotBooking",
            "0003_remove_booking_luggage_remove_booking_passanger_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="passanger_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="destination",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="flight", name="origin", field=models.CharField(max_length=3),
        ),
    ]
