# Generated by Django 4.2.17 on 2025-01-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AerolotBooking", "0004_alter_booking_passanger_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
